Feature/iznamenskiy/conv imad tgl improvements ngraph rebase
lznamens/openvino pull request #3
Opened 2020-12-30 14:32 UTC by lznamens

2020-12-30 18:04 UTC, sshlyapn reviewed
In general looks good to ne

2021-01-11 08:05 UTC, lznamens commented on inference-engine/thirdparty/clDNN/src/gpu/device_info.cpp
> +    const std::vector<std::pair<int, int> > dpas_ids_array = {
I read that some compilers can interpret the same construction as a right bit-shift.

2021-01-11 19:07 UTC, vladimir-paramuzov requested changes

2021-01-11 19:07 UTC, vladimir-paramuzov commented on inference-engine/thirdparty/clDNN/kernel_selector/core/kernel_selector_params.h
> +    uint32_t threadsPerComputeUnit = 0;
maxThreadsPerExecutionUnit

2021-01-12 04:17 UTC, closed without merging